// Question bank for the Automation Technology 1 final practice exam.
// Authoring rule: opts[0] is always the correct answer — options are shuffled at runtime.
// `ref` is the id of a section in Part 2 (Study Notes); `topic` groups questions for the evaluation.
const m = String.raw;

window.TOPICS = [
  { key: "ik-basics", name: "Kinematics basics & Atan2", week: "W11", refs: ["kinematics", "atan2"] },
  { key: "ik-planar", name: "2-link planar inverse kinematics", week: "W11", refs: ["ik-2link", "ik-theta1", "multiple-solutions", "worked-example"] },
  { key: "ik-3d", name: "3D arms: RRR, offset & RRP", week: "W11", refs: ["rrr", "offset", "rrp"] },
  { key: "sensors", name: "Sensor fundamentals & sensor types", week: "W13", refs: ["sensor-what", "sensor-stages", "sensor-types"] },
  { key: "smart", name: "Smart sensors", week: "W13", refs: ["smart-sensor", "smart-block", "smart-vs-traditional"] },
  { key: "impact", name: "Sensors in industrial automation", week: "W13", refs: ["sensor-impact"] },
  { key: "interface", name: "Interface systems", week: "W14", refs: ["interface", "interface-types"] },
  { key: "nodered", name: "Node-RED editor & flows", week: "W14", refs: ["nodered-what", "nodered-first-flow", "nodered-editor", "nodered-nodes", "nodered-subflows", "nodered-import", "nodered-sidebar", "assignment-temp"] },
  { key: "plc", name: "FX5U ↔ Node-RED (SLMP / MC protocol)", week: "W15", refs: ["plc-why", "fx5u-protocols", "fx5u-slmp", "nodered-mc", "assignment-fx5u"] },
  { key: "modbus", name: "Industrial protocols & Modbus TCP", week: "W16", refs: ["industrial-protocol", "interface-vs-protocol", "modbus", "modbus-fc", "modbus-fx5u", "modbus-nodered"] },
];

window.QUESTIONS = [
  // ───────────── W11 · Kinematics basics & Atan2 ─────────────
  { id: "k1", topic: "ik-basics", ref: "kinematics", concept: "Forward vs inverse kinematics",
    q: m`You know all six joint angles \(\theta_1 \dots \theta_6\) of a robot and want to find the end-effector pose \((X, Y, Z, R_x, R_y, R_z)\). Which problem are you solving?`,
    img: "img/w11-p05.jpg",
    opts: ["Forward kinematics", "Inverse kinematics", "Inverse dynamics", "Trajectory interpolation"],
    ex: m`<b>Forward kinematics</b>: joint angles → end-effector pose. <b>Inverse kinematics</b> is the reverse: pose → joint angles.` },

  { id: "k2", topic: "ik-basics", ref: "kinematics", concept: "Nature of the IK solution",
    q: m`Which statement about <b>inverse kinematics</b> matches the lecture?`,
    opts: ["The solution can be difficult to find and is not unique",
           "There is always exactly one set of joint angles for a target",
           "It computes the end-effector position from known joint angles",
           "It can only be solved numerically, never analytically"],
    ex: m`IK finds the joint variables for a given end-effector position and orientation. The slides stress that the <b>solution is difficult to find and is not unique</b> (e.g. arm-up and arm-down both reach the same point).` },

  { id: "k3", topic: "ik-basics", ref: "kinematics", concept: "Two analytical IK approaches",
    q: m`What are the two primary analytical approaches to inverse kinematics?`,
    opts: ["Geometric and Algebraic", "Forward and Backward", "Numerical and Graphical", "Jacobian and Iterative"],
    ex: m`The lecture compares the <b>Geometric</b> approach (triangles and the law of cosines) with the <b>Algebraic</b> approach. The worked derivations use the geometric one.` },

  { id: "k4", topic: "ik-basics", ref: "atan2", concept: "Why Atan2 instead of tan⁻¹",
    q: m`Why do the IK formulas use \(\operatorname{Atan2}(y, x)\) instead of \(\tan^{-1}(y/x)\)?`,
    img: "img/w11-p14.jpg",
    opts: ["Atan2 keeps the signs of x and y, so it knows which quadrant the angle is in",
           "Atan2 is faster to compute on a PLC",
           "tan⁻¹ only works in radians while Atan2 works in degrees",
           "Atan2 always returns a positive angle, which avoids negative joint values"],
    ex: m`\(\tan\theta = y/x\) gives the same value for quadrant I \((+,+)\) and quadrant III \((-,-)\). This is the slide's "critical loss of spatial awareness". <b>Atan2 uses both signs</b>, so the robot identifies the correct physical quadrant.` },

  { id: "k5", topic: "ik-basics", ref: "atan2", concept: "Evaluating Atan2 in quadrant III",
    q: m`A target is at \((x, y) = (-3, -3)\). What does \(\operatorname{Atan2}(y, x)\) return?`,
    opts: [m`\(-135^\circ\) (equivalent to \(225^\circ\))`, m`\(45^\circ\)`, m`\(135^\circ\)`, m`\(-45^\circ\)`],
    ex: m`\(\tan^{-1}(-3/-3) = \tan^{-1}(1) = 45^\circ\), which is wrong because it points into quadrant I. Atan2 sees that both x and y are negative, so the angle is in quadrant III: \(-135^\circ \equiv 225^\circ\).` },

  { id: "k6", topic: "ik-basics", ref: "rrp", concept: "Meaning of R and P joints",
    q: m`In the configuration names <b>RRR</b> and <b>RRP</b>, what do the letters stand for?`,
    opts: ["R = Revolute (rotating) joint, P = Prismatic (sliding / extending) joint",
           "R = Rigid link, P = Pivot joint",
           "R = Rotary encoder, P = Pneumatic actuator",
           "R = Radius, P = Position"],
    ex: m`<b>R</b>evolute joints rotate by an angle θ. A <b>P</b>rismatic joint extends linearly by a distance d. RRP = two rotations + one linear extension \(d_3\).` },

  // ───────────── W11 · 2-link planar IK ─────────────
  { id: "p1", topic: "ik-planar", ref: "ik-2link", concept: "Supplementary angle step (cos θc = −cos θ2)",
    q: m`The law of cosines gives \(c^2 = a_1^2 + a_2^2 - 2a_1a_2\cos\theta_c\). Why can we rewrite it as \(c^2 = a_1^2 + a_2^2 + 2a_1a_2\cos\theta_2\)?`,
    img: "img/w11-p09.jpg",
    opts: [m`\(\theta_c\) and \(\theta_2\) lie on a straight line, so \(\theta_c + \theta_2 = \pi\) and \(\cos\theta_c = -\cos\theta_2\)`,
           m`\(\theta_c = \theta_2\) because they are opposite angles`,
           m`\(\theta_c + \theta_2 = \pi/2\), so \(\cos\theta_c = \sin\theta_2\)`,
           m`The sign changes because \(c\) is measured from the end effector to the base`],
    ex: m`They are <b>supplementary</b>: \(\theta_c + \theta_2 = \pi\). Since \(\cos(\pi - \theta_2) = -\cos\theta_2\), the minus sign flips to a plus.` },

  { id: "p2", topic: "ik-planar", ref: "ik-2link", concept: "cos θ2 = D formula",
    q: m`For a 2-link planar arm with link lengths \(a_1, a_2\) reaching point \((x, y)\), which expression equals \(\cos\theta_2 = D\)?`,
    opts: [m`\(\dfrac{x^2 + y^2 - a_1^2 - a_2^2}{2a_1a_2}\)`,
           m`\(\dfrac{a_1^2 + a_2^2 - x^2 - y^2}{2a_1a_2}\)`,
           m`\(\dfrac{x^2 + y^2 + a_1^2 + a_2^2}{2a_1a_2}\)`,
           m`\(\dfrac{x^2 + y^2 - a_1^2 - a_2^2}{a_1a_2}\)`],
    ex: m`With \(c^2 = x^2 + y^2\): \(\cos\theta_2 = \dfrac{x^2+y^2-a_1^2-a_2^2}{2a_1a_2} = D\). The second option is \(\cos\theta_c\) (the interior angle), which is the negative of D.` },

  { id: "p3", topic: "ik-planar", ref: "ik-2link", concept: "Computing D",
    q: m`A 2-link arm has \(a_1 = 4\) and \(a_2 = 3\). The target is \((5, 3)\). What is \(D\)?`,
    opts: [m`\(0.375\)`, m`\(0.625\)`, m`\(-0.375\)`, m`\(2.458\)`],
    ex: m`\(D = \dfrac{5^2 + 3^2 - 4^2 - 3^2}{2(4)(3)} = \dfrac{25 + 9 - 16 - 9}{24} = \dfrac{9}{24} = 0.375\)` },

  { id: "p4", topic: "ik-planar", ref: "ik-2link", concept: "θ2 = Atan2(±√(1−D²), D)",
    q: m`Continuing: with \(D = 0.375\), what are the possible values of \(\theta_2\)?`,
    opts: [m`\(\theta_2 = \pm 67.98^\circ\)`, m`\(\theta_2 = \pm 22.02^\circ\)`, m`\(\theta_2 = \pm 112.02^\circ\)`, m`\(\theta_2 = +67.98^\circ\) only`],
    ex: m`\(\sqrt{1 - D^2} = \sqrt{1 - 0.1406} = 0.927\). \(\theta_2 = \operatorname{Atan2}(\pm 0.927,\ 0.375) = \pm 67.98^\circ\). Two signs → two configurations.` },

  { id: "p5", topic: "ik-planar", ref: "ik-theta1", concept: "θ1 formula for 2-link arm",
    q: m`Which formula gives \(\theta_1\) once \(\theta_2\) is known?`,
    img: "img/w11-p13.jpg",
    opts: [m`\(\theta_1 = \operatorname{Atan2}(y, x) - \operatorname{Atan2}(a_2\sin\theta_2,\ a_1 + a_2\cos\theta_2)\)`,
           m`\(\theta_1 = \operatorname{Atan2}(x, y) - \operatorname{Atan2}(a_2\sin\theta_2,\ a_1 + a_2\cos\theta_2)\)`,
           m`\(\theta_1 = \operatorname{Atan2}(y, x) + \operatorname{Atan2}(a_1 + a_2\cos\theta_2,\ a_2\sin\theta_2)\)`,
           m`\(\theta_1 = \operatorname{Atan2}(y, x) - \theta_2\)`],
    ex: m`\(\theta_1 = \omega - \phi\), where \(\omega = \operatorname{Atan2}(y, x)\) is the angle of the line to the target and \(\phi = \operatorname{Atan2}(a_2\sin\theta_2,\ a_1 + a_2\cos\theta_2)\) is the angle between link 1 and that line.` },

  { id: "p6", topic: "ik-planar", ref: "ik-theta1", concept: "Computing θ1 numerically",
    q: m`Same arm (\(a_1 = 4\), \(a_2 = 3\), target \((5, 3)\)). If \(\theta_2 = +67.98^\circ\) is chosen, what is \(\theta_1\)?`,
    opts: [m`\(\theta_1 \approx 2.48^\circ\)`, m`\(\theta_1 \approx 59.45^\circ\)`, m`\(\theta_1 \approx 30.96^\circ\)`, m`\(\theta_1 \approx 28.49^\circ\)`],
    ex: m`\(\operatorname{Atan2}(3, 5) = 30.96^\circ\). \(\phi = \operatorname{Atan2}(3\sin 67.98^\circ,\ 4 + 3\cos 67.98^\circ) = \operatorname{Atan2}(2.781, 5.125) = 28.49^\circ\). So \(\theta_1 = 30.96 - 28.49 = 2.48^\circ\). (With \(\theta_2 = -67.98^\circ\) you get \(59.45^\circ\).) Check: \(x = 4\cos 2.48^\circ + 3\cos 70.46^\circ = 5.00\) ✓` },

  { id: "p7", topic: "ik-planar", ref: "multiple-solutions", concept: "Meaning of ± (two configurations)",
    q: m`In \(\theta_2 = \operatorname{Atan2}(\pm\sqrt{1 - D^2},\ D)\), what does the \(\pm\) represent?`,
    img: "img/w11-p12.jpg",
    opts: ["The two possible arm configurations — arm (elbow) up and arm (elbow) down",
           "Clockwise and counter-clockwise rotation of the base",
           "The tolerance of the joint encoder",
           "Positive and negative values of the link length a₂"],
    ex: m`This is the <b>multiplicity of solutions</b>: the same point can be reached with the elbow above or below the line to the target. One sign gives the arm-up configuration, the other gives arm-down.` },

  { id: "p8", topic: "ik-planar", ref: "multiple-solutions", concept: "D > 1 means unreachable",
    q: m`While solving a 2-link arm you get \(D = 1.3\). What does this mean?`,
    opts: [m`The target is outside the workspace — \(1 - D^2 < 0\), so there is no real solution`,
           m`There are four solutions instead of two`,
           m`\(\theta_2 = 0^\circ\) (the arm is fully stretched)`,
           m`You must use \(\tan^{-1}\) instead of Atan2`],
    ex: m`\(D = \cos\theta_2\) must be between −1 and 1. \(D > 1\) means \(\sqrt{1 - D^2}\) is imaginary: the point is farther than \(a_1 + a_2\) (or closer than \(|a_1 - a_2|\)), so <b>the arm cannot reach it</b>. \(D = 1\) exactly means fully stretched (\(\theta_2 = 0\)).` },

  { id: "p9", topic: "ik-planar", ref: "multiple-solutions", concept: "Special case D = 0",
    q: m`A 2-link arm has \(a_1 = a_2 = 2\) and the target is \((2, 2)\). What is \(\theta_2\)?`,
    opts: [m`\(\pm 90^\circ\)`, m`\(\pm 45^\circ\)`, m`\(0^\circ\)`, m`\(\pm 60^\circ\)`],
    ex: m`\(D = \dfrac{4 + 4 - 4 - 4}{2 \cdot 2 \cdot 2} = 0\). \(\theta_2 = \operatorname{Atan2}(\pm 1, 0) = \pm 90^\circ\). Then \(\theta_1 = 0^\circ\) (for +90°) or \(90^\circ\) (for −90°).` },

  { id: "p10", topic: "ik-planar", ref: "worked-example", concept: "Lecture Example 1 (a₁=3, a₂=5)",
    q: m`Lecture Example 1: \(a_1 = 3\), \(a_2 = 5\), target \((2.0,\ 7.5)\). What are \(D\) and \(\theta_2\)?`,
    img: "img/w11-p22.jpg",
    opts: [m`\(D = 0.875\), \(\theta_2 = \pm 28.96^\circ\)`, m`\(D = 0.484\), \(\theta_2 = \pm 61.04^\circ\)`,
           m`\(D = 0.875\), \(\theta_2 = \pm 61.04^\circ\)`, m`\(D = 1.125\), no solution`],
    ex: m`\(D = \dfrac{7.5^2 + 2^2 - 3^2 - 5^2}{2 \cdot 3 \cdot 5} = \dfrac{26.25}{30} = 0.875\), \(\sqrt{1 - D^2} = 0.484\), so \(\theta_2 = \operatorname{Atan2}(\pm 0.484, 0.875) = \pm 28.96^\circ\). <i>Note: for θ₁ the slide evaluates Atan2(2, 7.5) = 14.93°, but Atan2(y, x) = Atan2(7.5, 2) = 75.07°. The correct θ₁ values are 56.90° and 93.24° — see the notes.</i>` },

  // ───────────── W11 · 3D arms ─────────────
  { id: "d1", topic: "ik-3d", ref: "rrr", concept: "2D → 3D projection (r and s)",
    q: m`An RRR robot is solved as a 2-link planar arm rotating on a base axis. The planar coordinates are replaced by what?`,
    img: "img/w11-p15.jpg",
    opts: [m`Projected radius \(r = \sqrt{x_c^2 + y_c^2}\) and vertical height \(s = z_c - d_1\)`,
           m`\(r = x_c + y_c\) and \(s = z_c\)`,
           m`\(r = z_c - d_1\) and \(s = \sqrt{x_c^2 + y_c^2}\)`,
           m`\(r = \sqrt{x_c^2 + y_c^2 + z_c^2}\) and \(s = d_1\)`],
    ex: m`Variable translation: base x → <b>projected radius r</b>, base y → <b>vertical height s</b>. \(r = \sqrt{x_c^2 + y_c^2}\), \(s = z_c - d_1\) (subtract the base height \(d_1\)).` },

  { id: "d2", topic: "ik-3d", ref: "rrr", concept: "RRR base rotation θ1",
    q: m`For an RRR arm with no offset, how is the base angle \(\theta_1\) found?`,
    img: "img/w11-p16.jpg",
    opts: [m`\(\theta_1 = \operatorname{Atan2}(y_c, x_c)\)`, m`\(\theta_1 = \operatorname{Atan2}(z_c - d_1, r)\)`,
           m`\(\theta_1 = \operatorname{Atan2}(x_c, y_c)\)`, m`\(\theta_1 = \cos^{-1}(D)\)`],
    ex: m`The base just points the arm plane at the target: \(\theta_1 = \operatorname{Atan2}(y_c, x_c)\). Another valid solution is \(\operatorname{Atan2}(y_c, x_c) + \pi\) (reaching back over the base).` },

  { id: "d3", topic: "ik-3d", ref: "rrr", concept: "Computing r and s",
    q: m`An RRR arm has base height \(d_1 = 1\). The target is \((x_c, y_c, z_c) = (3, 4, 2)\). What are \(r\) and \(s\)?`,
    opts: [m`\(r = 5,\ s = 1\)`, m`\(r = 5,\ s = 2\)`, m`\(r = 7,\ s = 1\)`, m`\(r = \sqrt{29},\ s = 1\)`],
    ex: m`\(r = \sqrt{3^2 + 4^2} = 5\), \(s = z_c - d_1 = 2 - 1 = 1\). (\(\theta_1 = \operatorname{Atan2}(4, 3) = 53.13^\circ\).)` },

  { id: "d4", topic: "ik-3d", ref: "rrr", concept: "RRR elbow angle θ3",
    q: m`Same arm with \(a_2 = 4\) and \(a_3 = 3\), and \(r = 5\), \(s = 1\). What is the elbow angle \(\theta_3\)?`,
    opts: [m`\(\theta_3 \approx \pm 87.61^\circ\)`, m`\(\theta_3 \approx \pm 92.39^\circ\)`, m`\(\theta_3 \approx \pm 53.13^\circ\)`, m`\(\theta_3 \approx \pm 36.87^\circ\)`],
    ex: m`\(D = \dfrac{r^2 + s^2 - a_2^2 - a_3^2}{2a_2a_3} = \dfrac{25 + 1 - 16 - 9}{24} = 0.0417\). \(\theta_3 = \operatorname{Atan2}(\pm\sqrt{1 - D^2}, D) = \pm 87.61^\circ\).` },

  { id: "d5", topic: "ik-3d", ref: "rrr", concept: "Second valid θ1 for RRR",
    q: m`Besides \(\theta_1 = \operatorname{Atan2}(y_c, x_c)\), which other base angle is also valid for an RRR arm with no offset?`,
    opts: [m`\(\theta_1 = \operatorname{Atan2}(y_c, x_c) + \pi\)`, m`\(\theta_1 = -\operatorname{Atan2}(y_c, x_c)\)`,
           m`\(\theta_1 = \operatorname{Atan2}(y_c, x_c) + \pi/2\)`, m`There is no other valid solution`],
    ex: m`Rotating the base by \(\pi\) and bending the shoulder backwards over the top reaches the same point, so \(\operatorname{Atan2}(y_c, x_c) + \pi\) is also valid.` },

  { id: "d6", topic: "ik-3d", ref: "offset", concept: "Left arm vs right arm (offset)",
    q: m`For an RRR arm with a shoulder <b>offset d</b>, what distinguishes the Left-Arm and Right-Arm configurations?`,
    img: "img/w11-p17.jpg",
    opts: ["Whether the elbow bends to the left or to the right of the target line",
           "Whether the robot is mounted on the left or right side of the conveyor",
           "Whether θ₃ is positive or negative",
           "Whether the offset d is added to or subtracted from the base height d₁"],
    ex: m`"The Offset Illusion" slide: <b>Left arm</b> — the elbow bends left of the target line. <b>Right arm</b> — the elbow bends right of it. Each needs its own θ₁ modifier formula.` },

  { id: "d7", topic: "ik-3d", ref: "offset", concept: "Effective radius with offset √(x²+y²−d²)",
    q: m`With a shoulder offset \(d\), the in-plane radius used for the planar sub-problem is \(\sqrt{x_c^2 + y_c^2 - d^2}\). For \(x_c = 4\), \(y_c = 3\), \(d = 3\), what is it?`,
    opts: [m`\(4\)`, m`\(5\)`, m`\(\sqrt{34}\)`, m`\(2\)`],
    ex: m`\(\sqrt{16 + 9 - 9} = \sqrt{16} = 4\). The offset \(d\) is perpendicular to the arm plane, so by Pythagoras the usable radius shrinks from \(\sqrt{x_c^2 + y_c^2} = 5\) to 4.` },

  { id: "d8", topic: "ik-3d", ref: "offset", concept: "Left-arm θ1 modifier formula",
    q: m`Which is the <b>Left-Arm</b> base-angle formula for an RRR arm with offset \(d\)?`,
    img: "img/w11-p18.jpg",
    opts: [m`\(\theta_1 = \operatorname{Atan2}(y_c, x_c) - \operatorname{Atan2}\!\left(\sqrt{x_c^2 + y_c^2 - d^2},\ d\right)\)`,
           m`\(\theta_1 = \operatorname{Atan2}(y_c, x_c) + \operatorname{Atan2}\!\left(-\sqrt{x_c^2 + y_c^2 - d^2},\ -d\right)\)`,
           m`\(\theta_1 = \operatorname{Atan2}(y_c, x_c) - d\)`,
           m`\(\theta_1 = \operatorname{Atan2}\!\left(d,\ \sqrt{x_c^2 + y_c^2}\right)\)`],
    ex: m`Left arm: \(\theta_1 = \phi - \alpha = \operatorname{Atan2}(y_c, x_c) - \operatorname{Atan2}(\sqrt{x_c^2+y_c^2-d^2},\ d)\). The second option is the <b>Right-Arm</b> formula (\(\theta_1 = \alpha + \beta\), with \(\beta = \gamma + \pi\)).` },

  { id: "d9", topic: "ik-3d", ref: "rrp", concept: "Why RRP IK is simpler",
    q: m`Why is inverse kinematics for an <b>RRP</b> arm simpler than for an <b>RRR</b> arm?`,
    img: "img/w11-p19.jpg",
    opts: ["The last joint is prismatic, so its output d₃ comes from the Pythagorean theorem instead of the law of cosines",
           "RRP arms have fewer links, so they need no base rotation θ₁",
           "RRP arms always have two solutions for d₃",
           "Prismatic joints do not need Atan2"],
    ex: m`RRR needs an angle \(\theta_3\), found with the law of cosines (high complexity). RRP needs a <b>linear distance</b> \(d_3 = \sqrt{r^2 + s^2}\), found with the basic Pythagorean theorem (low complexity).` },

  { id: "d10", topic: "ik-3d", ref: "rrp", concept: "RRP extension d3",
    q: m`An RRP arm has \(d_1 = 2\). The target is \((3, 4, 5)\). What is the extension \(d_3\)?`,
    img: "img/w11-p20.jpg",
    opts: [m`\(d_3 = \sqrt{34} \approx 5.83\)`, m`\(d_3 = \sqrt{50} \approx 7.07\)`, m`\(d_3 = 5\)`, m`\(d_3 = 3\)`],
    ex: m`\(r = \sqrt{3^2 + 4^2} = 5\), \(s = z_c - d_1 = 3\). \(d_3 = \sqrt{r^2 + s^2} = \sqrt{25 + 9} = \sqrt{34} \approx 5.83\). (Forgetting to subtract \(d_1\) gives \(\sqrt{50}\).)` },

  { id: "d11", topic: "ik-3d", ref: "rrp", concept: "RRP elevation θ2 = Atan2(s, r)",
    q: m`For the same RRP arm (\(r = 5\), \(s = 3\)), what is the elevation angle \(\theta_2\)?`,
    opts: [m`\(\theta_2 = \operatorname{Atan2}(s, r) \approx 30.96^\circ\)`, m`\(\theta_2 = \operatorname{Atan2}(r, s) \approx 59.04^\circ\)`,
           m`\(\theta_2 = \operatorname{Atan2}(4, 3) \approx 53.13^\circ\)`, m`\(\theta_2 \approx 36.87^\circ\)`],
    ex: m`The elevation is measured up from the horizontal radius r: \(\theta_2 = \operatorname{Atan2}(s, r) = \operatorname{Atan2}(3, 5) = 30.96^\circ\). \(\operatorname{Atan2}(4, 3) = 53.13^\circ\) is the base angle \(\theta_1\).` },

  // ───────────── W13 · Sensor fundamentals ─────────────
  { id: "s1", topic: "sensors", ref: "sensor-what", concept: "Definition of a sensor",
    q: m`Which is the lecture's definition of a <b>sensor</b>?`,
    opts: ["A device that detects physical changes and converts them into electrical signals",
           "A device that converts electrical signals into mechanical motion",
           "A controller that makes decisions from input data",
           "A network device that transmits data between PLCs"],
    ex: m`"A sensor is a device that <b>detects physical changes</b> and <b>converts them into electrical signals</b>." Converting electrical signals into motion is what an actuator does.` },

  { id: "s2", topic: "sensors", ref: "sensor-stages", concept: "Order of the 4 sensor stages",
    q: m`What is the correct order of how a sensor works?`,
    img: "img/w13-p07.jpg",
    opts: ["Detection → Conversion (transduction) → Signal conditioning → Output",
           "Conversion → Detection → Output → Signal conditioning",
           "Detection → Signal conditioning → Conversion → Output",
           "Signal conditioning → Detection → Conversion → Output"],
    ex: m`1) Detect the physical phenomenon → 2) Convert (transduce) it into an electrical signal → 3) Condition the signal (amplify, filter, linearize, reduce noise) → 4) Output an analog or digital signal to a PLC, MCU, DAQ or display.` },

  { id: "s3", topic: "sensors", ref: "sensor-stages", concept: "What signal conditioning does",
    q: m`Which of these is <b>NOT</b> part of <i>signal conditioning</i>?`,
    opts: ["Converting the physical change into an electrical signal", "Amplification", "Filtering and noise reduction", "Linearization"],
    ex: m`Converting the physical change into an electrical signal is <b>stage 2, transduction</b>. Signal conditioning (stage 3) improves an existing electrical signal: amplification, filtering, linearization and noise reduction.` },

  { id: "s4", topic: "sensors", ref: "sensor-stages", concept: "Signal right after transduction",
    q: m`Right after the conversion (transduction) stage, what is the signal typically like?`,
    opts: ["Weak, analog, and not yet suitable for direct use", "Strong, digital, and ready for a PLC",
           "Already filtered and linearized", "Encoded as a Modbus register"],
    ex: m`The slide says: "At this stage, the signal is typically <b>weak, analog, and not yet suitable for direct use</b>." That is why signal conditioning follows.` },

  { id: "s5", topic: "sensors", ref: "sensor-types", concept: "Capacitive proximity sensor",
    q: m`You must detect the <b>level of plastic granules</b> inside a hopper, and the target is non-metallic. Which sensor fits best?`,
    img: "img/w13-p08.jpg",
    opts: ["Capacitive proximity sensor", "Inductive proximity sensor", "Rotary encoder", "Load cell"],
    ex: m`<b>Capacitive</b> sensors detect <b>both metallic and non-metallic</b> objects — solids, liquids and granular materials. They are ideal for level detection. Sensing distance depends on the target's <b>dielectric constant</b>. Inductive sensors detect metal only.` },

  { id: "s6", topic: "sensors", ref: "sensor-types", concept: "Inductive proximity sensor",
    q: m`Which sensor detects <b>metal targets only</b>, is non-contact, is resistant to dust, oil and vibration, and is used for RPM monitoring and position sensing?`,
    img: "img/w13-p10.jpg",
    opts: ["Inductive proximity sensor", "Capacitive proximity sensor", "Fiber-optic photoelectric sensor", "Thermal sensor"],
    ex: m`<b>Inductive proximity sensors</b> detect metal only. Uses: position sensing, transport monitoring, pulse generation, RPM monitoring, detection of rotation, feed/reject control, monitoring of idle running.` },

  { id: "s7", topic: "sensors", ref: "sensor-types", concept: "Fiber-optic photoelectric sensor",
    q: m`A pick-and-place machine must detect <b>tiny electronic components</b> in a very tight, hot space. Which sensor is recommended?`,
    img: "img/w13-p09.jpg",
    opts: ["Fiber-optic photoelectric sensor", "Load cell", "Inductive proximity sensor", "Safety light curtain"],
    ex: m`In a <b>fiber-optic photoelectric sensor</b>, the transmitter and receiver connect through fiber cables. It is ideal for tiny objects and limited installation space, and it suits high-temperature, harsh environments.` },

  { id: "s8", topic: "sensors", ref: "sensor-what", concept: "Common sensor types (encoder, load cell…)",
    q: m`Which device <b>converts rotational or linear motion</b> into digital or analog electrical signals?`,
    img: "img/w13-p06.jpg",
    opts: ["Encoder", "Load cell", "Safety light curtain", "Pressure sensor"],
    ex: m`<b>Encoder</b>: motion → signals. <b>Load cell</b>: force/weight via mechanical deformation. <b>Safety light curtain</b>: multiple light beams detect intrusion. <b>Pressure sensor</b>: gas/liquid pressure → proportional signal.` },

  // ───────────── W13 · Smart sensors ─────────────
  { id: "m1", topic: "smart", ref: "smart-sensor", concept: "Definition of a smart sensor",
    q: m`What makes a sensor a <b>smart sensor</b>?`,
    img: "img/w13-p12.jpg",
    opts: ["Built-in signal processing, intelligence, and communication capabilities",
           "It uses a larger sensing element for higher range",
           "It outputs a 4–20 mA analog signal",
           "It can only be read by a PLC"],
    ex: m`"A smart sensor is a sensor with <b>built-in signal processing, intelligence, and communication</b> capabilities." It can process data before passing it on.` },

  { id: "m2", topic: "smart", ref: "smart-sensor", concept: "4 main functions (Verification = self-diagnostics)",
    q: m`A smart sensor has 4 main functions. Which function covers <b>self-diagnostics</b>, i.e. nonstop supervision of the sensor's own behavior?`,
    opts: ["Verification", "Configuration", "Measurement", "Communication"],
    ex: m`<b>Measurement</b> — measures physical quantities. <b>Configuration</b> — setup and calibration (detects position/installation errors). <b>Verification</b> — self-diagnostics. <b>Communication</b> — exchanges data with external devices.` },

  { id: "m3", topic: "smart", ref: "smart-block", concept: "Block diagram order (ADC after conditioning)",
    q: m`In the smart sensor block diagram, which block comes <b>directly after</b> Signal Conditioning?`,
    img: "img/w13-p14.jpg",
    opts: ["Analog-to-Digital Conversion", "Application Algorithms", "Communication Unit", "Memory"],
    ex: m`Sensing Unit → Signal Conditioning → <b>ADC</b> → Application Algorithms. Memory, the Local User Interface and the Communication Unit all connect two-way to the Application Algorithms.` },

  { id: "m4", topic: "smart", ref: "smart-block", concept: "Communication unit role",
    q: m`Which smart-sensor block sends output signals to the main station <b>and</b> receives commands from it?`,
    opts: ["Communication Unit / Transceiver", "Local User Interface", "Memory", "Sensing Unit"],
    ex: m`The <b>communication unit</b> transmits outputs from the application algorithm to the main station and also receives command requests to execute tasks. The LUI is a panel-mounted device for operators; Memory stores data.` },

  { id: "m5", topic: "smart", ref: "smart-vs-traditional", concept: "Traditional vs smart sensor",
    q: m`Which row correctly compares a <b>traditional</b> sensor with a <b>smart</b> sensor?`,
    img: "img/w13-p19.jpg",
    opts: ["Traditional: analog, no diagnostics, processed by PLC — Smart: digital, self-diagnostics, processed by MCU",
           "Traditional: digital, self-diagnostics — Smart: analog, no diagnostics",
           "Traditional: detect + process — Smart: detect only",
           "Both are analog; only smart sensors are waterproof"],
    ex: m`Traditional (e.g. inductive sensor): <b>detect</b>, analog, no diagnostics, PLC does the processing. Smart (e.g. IO-Link sensor): <b>detect + process</b>, digital, self-diagnostics, MCU inside does the processing.` },

  // ───────────── W13 · Impact on industry ─────────────
  { id: "i1", topic: "impact", ref: "sensor-impact", concept: "Predictive maintenance (vibration)",
    q: m`A vibration sensor is mounted on motor bearings. Which key contribution of sensors does this mainly support?`,
    opts: ["Fault detection and predictive maintenance", "Energy efficiency", "Inventory management", "Quality improvement of the product"],
    ex: m`Vibration sensors detect abnormal conditions early to <b>prevent equipment failure</b>. The sensor-type table lists vibration → "Predictive Maintenance, Motor & Bearing Monitoring".` },

  { id: "i2", topic: "impact", ref: "sensor-impact", concept: "Sensor types ↔ industrial applications",
    q: m`According to the lecture table, which pairing of sensor type and typical application is correct?`,
    opts: ["Proximity sensor — conveyor systems, position detection, part counting",
           "Flow sensor — motor and bearing monitoring",
           "Pressure sensor — part counting on conveyors",
           "Temperature sensor — pipeline flow rate"],
    ex: m`Temperature → HVAC, furnaces, boilers. Pressure → hydraulic/pneumatic systems, tanks, pipelines. Flow → water treatment, chemical, food. Vibration → predictive maintenance. <b>Proximity → conveyors, position detection, part counting.</b>` },

  { id: "i3", topic: "impact", ref: "sensor-impact", concept: "5 key contributions of sensors",
    q: m`Which is <b>NOT</b> one of the five key contributions of sensors in industrial automation listed in the lecture?`,
    opts: ["Replacing the PLC as the main controller", "Real-time monitoring and process control", "Energy efficiency", "Safety enhancement"],
    ex: m`The five contributions: ① real-time monitoring & process control, ② fault detection & predictive maintenance, ③ quality improvement, ④ energy efficiency, ⑤ safety enhancement. Sensors feed data to controllers; they do not replace the PLC.` },

  { id: "i4", topic: "impact", ref: "sensor-impact", concept: "Sensor → PLC → Node-RED → cloud architecture",
    q: m`In the lecture's architecture diagram, where does <b>Node-RED</b> sit?`,
    img: "img/w13-p26.jpg",
    opts: ["Between the PLC and the cloud / dashboards / database / alerts",
           "Between the sensors and the PLC inputs",
           "Inside the sensor, replacing signal conditioning",
           "Between the PLC outputs and the motors / valves"],
    ex: m`Sensors → PLC (→ outputs: lamps, contactors, motors, valves). Then PLC → <b>Node-RED</b> → cloud → laptops, tablets, phones, database, alarms. Node-RED is the integration layer above the PLC.` },

  // ───────────── W14 · Interface ─────────────
  { id: "f1", topic: "interface", ref: "interface", concept: "Definition of an interface",
    q: m`What is an <b>interface</b>?`,
    img: "img/w14-p06.jpg",
    opts: ["A connection point that allows two systems or devices to exchange information",
           "A set of rules that defines how data is formatted and interpreted",
           "A program that runs the PLC ladder logic",
           "A sensor that converts light into voltage"],
    ex: m`Interface = connection point → <b>Connect → Exchange Data → Work Together</b>. The second option describes a <b>protocol</b> (W16).` },

  { id: "f2", topic: "interface", ref: "interface-types", concept: "Hardware interface examples (UART, SPI, PCIe)",
    q: m`UART, SPI, PCIe slots and USB/HDMI/Ethernet ports are all examples of…`,
    opts: ["Hardware interfaces", "Software interfaces", "Application Programming Interfaces", "Industrial protocols only"],
    ex: m`<b>Hardware interface</b> = physical and electrical connection: external ports (USB, HDMI, Ethernet), internal slots (PCIe) and chip-level protocols (UART, SPI).` },

  { id: "f3", topic: "interface", ref: "interface-types", concept: "Software interface examples (API, GUI, CLI)",
    q: m`Which of these is a <b>software interface</b> that lets different software systems talk to each other over a network?`,
    opts: ["API (Application Programming Interface)", "RS-485 port", "PCIe slot", "RJ45 connector"],
    ex: m`Software interfaces: <b>UI</b> (GUI = icons/windows, CLI = typed text), <b>API</b> (software ↔ software) and programming/object interfaces (code contracts).` },

  { id: "f4", topic: "interface", ref: "interface-types", concept: "Cable alone ≠ communication",
    q: m`"If we connect a PLC and a computer using an Ethernet cable, can they communicate immediately?"`,
    opts: ["No — the cable is only the physical interface; both sides also need matching settings and a common protocol",
           "Yes — Ethernet automatically exchanges PLC data",
           "Yes, but only if the cable is shorter than 100 m",
           "No — Ethernet cannot be used with PLCs"],
    ex: m`A hardware interface only connects devices. To exchange meaningful data they also need a shared <b>protocol</b> and configuration (IP address, port, e.g. SLMP or Modbus TCP). That's the whole point of W15–W16.` },

  { id: "f5", topic: "interface", ref: "interface-types", concept: "Why we need an interface",
    q: m`Why do we need an interface / integration solution for a PLC?`,
    img: "img/w14-p09.jpg",
    opts: ["To collect, process, and deliver PLC data to other systems such as dashboards, databases, IoT and cloud",
           "To replace the PLC's I/O modules",
           "To increase the PLC's scan speed",
           "To convert the sensor's physical change into voltage"],
    ex: m`"We need an interface / integration solution to <b>collect, process and deliver PLC data</b> to various systems." It is the bridge to Dashboard, Database, IoT/MQTT and Cloud.` },

  // ───────────── W14 · Node-RED ─────────────
  { id: "n1", topic: "nodered", ref: "nodered-what", concept: "Node-RED is not a protocol",
    q: m`Which statement about <b>Node-RED</b> is correct?`,
    opts: ["It is a flow-based integration tool that works with different communication protocols — not a protocol itself",
           "It is an industrial communication protocol like Modbus",
           "It is Mitsubishi's PLC programming software",
           "It is a hardware gateway that must be installed in the control cabinet"],
    ex: m`"Node-RED is <b>not a communication protocol</b>. It is an <b>integration tool</b> that can work with different communication protocols." It is flow-based, low-code, and built on Node.js.` },

  { id: "n2", topic: "nodered", ref: "nodered-what", concept: "Built on Node.js (event-driven)",
    q: m`Node-RED is built on which runtime, making it suitable for low-cost edge hardware like a Raspberry Pi?`,
    opts: ["Node.js (event-driven, non-blocking)", "Python", "Java Virtual Machine", ".NET Framework"],
    ex: m`Node-RED is built on <b>Node.js</b>, using its event-driven, non-blocking model. It runs at the network edge (e.g. Raspberry Pi) as well as in the cloud.` },

  { id: "n3", topic: "nodered", ref: "nodered-first-flow", concept: "Editor URL / port 1880",
    q: m`With Node-RED running on your own PC, which URL opens the editor?`,
    opts: ["http://localhost:1880", "http://localhost:502", "http://localhost:9000", "http://localhost:8080/node-red"],
    ex: m`Default: <b>http://localhost:1880</b> (or http://&lt;ip-address&gt;:1880 from another computer). 502 is Modbus TCP; 9000 is the SLMP port used in class.` },

  { id: "n4", topic: "nodered", ref: "nodered-editor", concept: "4 editor components (palette)",
    q: m`In the Node-RED editor, where do you find the list of <b>nodes available to use</b>?`,
    img: "img/w14-p12.jpg",
    opts: ["The palette on the left", "The header at the top", "The sidebar on the right", "The workspace in the middle"],
    ex: m`① <b>Header</b> (top): Deploy button and main menu. ② <b>Palette</b> (left): available nodes. ③ <b>Workspace</b> (middle): where flows are built. ④ <b>Sidebar</b> (right): info, debug, etc.` },

  { id: "n5", topic: "nodered", ref: "nodered-first-flow", concept: "Deploy is required",
    q: m`You wired an Inject node to a Debug node, but clicking Inject shows nothing in the Debug sidebar. What did you most likely forget?`,
    opts: ["To click Deploy — nodes only exist in the editor until deployed to the server",
           "To install node-red-contrib-modbus",
           "To create a subflow",
           "To export the flow as JSON"],
    ex: m`"At this point, the nodes only exist in the editor and <b>must be deployed</b> to the server. Click the Deploy button."` },

  { id: "n6", topic: "nodered", ref: "nodered-first-flow", concept: "Inject default payload (timestamp ms)",
    q: m`By default, what payload does an <b>Inject</b> node send?`,
    opts: ["A timestamp — the number of milliseconds (since 1 Jan 1970)", "An empty string", "The text \"hello world\"", "The value true"],
    ex: m`"By default, the Inject node uses the <b>number of milliseconds</b> as its payload" — a timestamp. That's why numbers appear in the Debug sidebar.` },

  { id: "n7", topic: "nodered", ref: "nodered-nodes", concept: "Ports: max 1 input, many outputs",
    q: m`How many input and output ports can a Node-RED node have?`,
    opts: ["At most one input port, and many output ports", "Many input ports, and at most one output port",
           "Exactly one input and one output", "Unlimited inputs and outputs"],
    ex: m`"A node can have <b>at most one input port</b> and <b>many output ports</b>." The same rule applies to subflows.` },

  { id: "n8", topic: "nodered", ref: "nodered-nodes", concept: "Blue circle / red triangle indicators",
    q: m`A node shows a <b>blue circle</b> above it. What does that mean?`,
    img: "img/w14-p19.jpg",
    opts: ["It has undeployed changes", "Its configuration has errors", "It is currently connected to MQTT", "It is disabled"],
    ex: m`<b>Blue circle</b> = undeployed changes. <b>Red triangle</b> = configuration errors. Status text/icons below a node (e.g. MQTT "connected") show its runtime state.` },

  { id: "n9", topic: "nodered", ref: "nodered-nodes", concept: "Quick-Add dialog (Ctrl/Cmd + click)",
    q: m`How do you open the <b>Quick-Add</b> dialog to add a node where the mouse is?`,
    opts: ["Hold Ctrl (or Command) and click on the workspace", "Double-click on a wire", "Press Alt-a then n", "Right-click on the palette"],
    ex: m`Quick-Add is opened by <b>holding Ctrl/Command while clicking on the workspace</b>. Other ways to add nodes: drag from the palette, or import from the library/clipboard.` },

  { id: "n10", topic: "nodered", ref: "nodered-nodes", concept: "Only Inject & Debug have buttons",
    q: m`Which two <b>core</b> nodes are the only ones with a button on their edge in the editor?`,
    opts: ["Inject and Debug", "Function and Switch", "Change and Template", "MQTT in and MQTT out"],
    ex: m`"The <b>Inject and Debug</b> nodes are the only core nodes that have buttons." Inject's button fires a message; Debug's button toggles output.` },

  { id: "n11", topic: "nodered", ref: "nodered-nodes", concept: "Node edit dialog tabs",
    q: m`A node's edit dialog (opened by double-click or Enter) contains which three tabs?`,
    opts: ["Properties, Description, Appearance", "Settings, Queues, Optionals", "Nodes, Install, Palette", "Info, Debug, Context"],
    ex: m`Node edit dialog: <b>Properties</b> (node-specific form), <b>Description</b> (Markdown docs shown in the Info sidebar), <b>Appearance</b> (customize look). "Settings/Queues/Optionals" are tabs of the Modbus client config node.` },

  { id: "n12", topic: "nodered", ref: "nodered-subflows", concept: "Subflow definition & 1-input rule",
    q: m`What is a <b>subflow</b>, and when can a selection be converted into one?`,
    opts: ["A set of nodes collapsed into one reusable node; possible only if the wires coming into the selection connect to one node",
           "A flow tab that is disabled; possible at any time",
           "A group with a colored border; possible only if nodes are aligned to grid",
           "A copy of a flow in JSON; possible only after Deploy"],
    ex: m`A subflow collapses nodes into a single node that appears in the palette for reuse. "Selection to Subflow" works <b>only if incoming wires connect to one node</b>, because a subflow node can have at most one input.` },

  { id: "n13", topic: "nodered", ref: "nodered-subflows", concept: "Disabled flow behavior",
    q: m`What happens to a <b>disabled</b> flow when you deploy?`,
    opts: ["None of the nodes it contains are created", "Its nodes run but Debug output is hidden",
           "It is deleted from the workspace", "It is converted into a subflow"],
    ex: m`"If a flow is disabled, <b>none of the nodes it contains will be created</b> when the flow is deployed." You toggle it in the Flow Properties dialog or with the Info sidebar button.` },

  { id: "n14", topic: "nodered", ref: "nodered-import", concept: "Import/Export uses JSON",
    q: m`In which format are flows imported and exported in Node-RED?`,
    opts: ["JSON (compact or formatted)", "XML", "CSV", "Ladder (.gx3)"],
    ex: m`Flows are shared as <b>JSON</b>. Export can be <b>compact</b> (single line, no whitespace) or <b>formatted</b> (indented, easier to read) — to the clipboard, a file, or the local library.` },

  { id: "n15", topic: "nodered", ref: "nodered-import", concept: "Palette Manager",
    q: m`Where do you install a new node package such as <i>node-red-contrib-modbus</i>?`,
    opts: ["Palette Manager → Install tab (User Settings → Palette)", "Debug sidebar → filter", "Flow Properties → Environment Variables", "Arrange menu"],
    ex: m`The <b>Palette Manager</b> (User Settings → Palette) has two tabs: <b>Nodes</b> (installed modules — remove/disable/upgrade) and <b>Install</b> (search and install). A module in use cannot be removed or disabled.` },

  { id: "n16", topic: "nodered", ref: "nodered-sidebar", concept: "Debug sidebar filter options",
    q: m`The Debug sidebar filter offers which three options?`,
    opts: ["all nodes, selected nodes, current flow", "errors, warnings, info", "payload, topic, full msg", "inputs, outputs, functions"],
    ex: m`Filter options: <b>all nodes</b> (every message), <b>selected nodes</b> (pick specific Debug nodes), <b>current flow</b> (only the flow tab you are viewing).` },

  { id: "n17", topic: "nodered", ref: "nodered-what", concept: "Input → Process → Output model",
    q: m`In the "How does Node-RED work?" model, which node plays the <b>Process</b> role (convert units, calculate, add timestamp)?`,
    img: "img/w14-p41.jpg",
    opts: ["Function", "Inject", "Debug", "Palette"],
    ex: m`<b>Input</b>: Inject (e.g. simulated temperature 35 °C) → <b>Process</b>: Function (transform/filter/calculate) → <b>Output</b>: Debug (or a dashboard, database, MQTT).` },

  { id: "n18", topic: "nodered", ref: "assignment-temp", concept: "Temperature assignment thresholds",
    q: m`In the W14 temperature-monitoring assignment, a reading of exactly <b>60 °C</b> should be classified as…`,
    opts: ["OVERHEAT — the message must say \"MOTOR OVERHEAT\"", "WARNING", "NORMAL", "It depends on the previous reading"],
    ex: m`Switch-node rules: <b>T &lt; 40 °C → Normal</b>, <b>40 ≤ T &lt; 60 → Warning</b>, <b>T ≥ 60 → Overheat</b> ("MOTOR OVERHEAT"). 60 is included in Overheat.` },

  // ───────────── W15 · PLC ↔ Node-RED ─────────────
  { id: "c1", topic: "plc", ref: "plc-why", concept: "Reasons to connect PLC to Node-RED",
    q: m`Which is <b>NOT</b> one of the reasons listed for connecting a PLC to Node-RED?`,
    img: "img/w15-p06.jpg",
    opts: ["To replace the PLC's real-time control logic", "Web-based dashboard", "Data logging to files, databases or cloud", "IoT / cloud integration"],
    ex: m`Reasons: <b>real-time monitoring, web-based dashboard, data processing, data logging, IoT/cloud integration</b>. The PLC still runs the machine; Node-RED supervises (Dashboard → Node-RED → PLC → Machine).` },

  { id: "c2", topic: "plc", ref: "fx5u-protocols", concept: "FX5U recommended protocol (SLMP)",
    q: m`Which FX5U communication option is marked <b>Recommended</b> and gives access to full device memory at high speed?`,
    img: "img/w15-p07.jpg",
    opts: ["MC Protocol / SLMP", "Modbus TCP", "OPC UA", "MQTT"],
    ex: m`<b>MC Protocol / SLMP</b> is Mitsubishi's native protocol: high speed, access to full device memory, advanced functions. Modbus TCP is an open standard; OPC UA and MQTT need a server/gateway.` },

  { id: "c3", topic: "plc", ref: "fx5u-protocols", concept: "MQTT = lightweight publish/subscribe for IoT",
    q: m`Which protocol is described as a <b>lightweight publish/subscribe</b> protocol, ideal for IoT and cloud communication (used with FX5U via a gateway)?`,
    opts: ["MQTT", "OPC UA", "SLMP", "Modbus TCP"],
    ex: m`<b>MQTT</b> — lightweight, efficient, publish/subscribe, best for IoT devices, cloud platforms and remote monitoring. <b>OPC UA</b> — platform-independent, secure, best for MES/ERP/IT systems.` },

  { id: "c4", topic: "plc", ref: "fx5u-protocols", concept: "OPC UA characteristics",
    q: m`Which option is <b>platform independent, secure and scalable</b>, and best for enterprise systems like MES and ERP?`,
    opts: ["OPC UA (via OPC server / gateway)", "MQTT", "MC Protocol / SLMP", "RS-232"],
    ex: m`OPC UA: platform-independent, secure & reliable, scalable & extensible, ideal for enterprise systems (MES, ERP, IT).` },

  { id: "c5", topic: "plc", ref: "fx5u-slmp", concept: "GX Works3 path to Ethernet settings",
    q: m`In GX Works3, where do you set the FX5U's own IP address?`,
    img: "img/w15-p08.jpg",
    opts: ["Parameter → FX5UCPU → Module Parameter → Ethernet Port → Own Node Settings",
           "Parameter → System Parameter → CPU Parameter",
           "Navigation → Connection Destination → Serial",
           "Module Parameter → 485 Serial Port → Own Node Settings"],
    ex: m`<b>Module Parameter → Ethernet Port → Basic Settings → Own Node Settings</b>. In class: IP 192.168.3.36, subnet mask 255.255.255.0.` },

  { id: "c6", topic: "plc", ref: "fx5u-slmp", concept: "Adding SLMP connection module (TCP, port 9000)",
    q: m`To let Node-RED talk to the FX5U using SLMP, what is added under <b>External Device Configuration</b>?`,
    img: "img/w15-p10.jpg",
    opts: ["An SLMP Connection Module with protocol TCP and a port number (9000 in class)",
           "A MODBUS/TCP Connection Module on port 502",
           "A MELSOFT Connection Module on port 1880",
           "A GOT2000 HMI device"],
    ex: m`Drag <b>SLMP Connection Module</b> from Module List → Ethernet Device (General). Set Protocol = <b>TCP</b>, Port = <b>9000</b>. Then "Close with Reflecting the Setting" → Check → Apply, and write the parameters to the PLC.` },

  { id: "c7", topic: "plc", ref: "nodered-mc", concept: "node-red-contrib-mcprotocol settings",
    q: m`Which Node-RED package and connection settings were used to talk to the FX5U over SLMP in W15?`,
    img: "img/w15-p12.jpg",
    opts: ["node-red-contrib-mcprotocol — host 192.168.3.36, port 9000, frame 3E, TCP",
           "node-red-contrib-modbus — host 192.168.3.30, port 502, Unit-Id 1",
           "node-red-dashboard — host localhost, port 1880",
           "node-red-contrib-mcprotocol — host 192.168.3.36, port 502, frame 1E, UDP"],
    ex: m`<b>node-red-contrib-mcprotocol</b> provides MC Read / MC Write nodes. Connection node: Host 192.168.3.36, Port 9000, frame <b>3E</b>, protocol <b>TCP</b>, PLC type Q. (Option 2 is the W16 Modbus setup.)` },

  { id: "c8", topic: "plc", ref: "assignment-fx5u", concept: "FX5U device letters (X, Y, M, D)",
    q: m`In the FX5U assignment, which list correctly describes the device types <b>X, Y, M, D</b>?`,
    opts: ["X = input, Y = output, M = internal relay (bit), D = data register (word)",
           "X = output, Y = input, M = motor, D = digital input",
           "X = axis, Y = axis, M = memory card, D = display",
           "X = internal relay, Y = data register, M = input, D = output"],
    ex: m`X0 START, X1 STOP, X2 photoelectric sensor (<b>inputs</b>). Y0 motor, Y1 green lamp, Y2 red lamp (<b>outputs</b>). M0 run status (<b>internal bit</b>). D0 workpiece count (<b>data register</b>).` },

  { id: "c9", topic: "plc", ref: "assignment-fx5u", concept: "Bonus: D0 ≥ 20 → M20 → Y2",
    q: m`Bonus challenge: when the production count reaches <b>D0 ≥ 20</b>, what must happen?`,
    opts: ["Node-RED shows PRODUCTION TARGET REACHED, activates a dashboard alarm and writes M20; the PLC then turns ON red lamp Y2",
           "The PLC resets D0 to 0 and stops the motor Y0 automatically",
           "Node-RED directly switches the Y2 output without the PLC program",
           "The green lamp Y1 flashes and M0 turns OFF"],
    ex: m`Node-RED: display "PRODUCTION TARGET REACHED", activate the dashboard alarm, <b>send a command to M20</b>. PLC: M20 → <b>turn ON red lamp Y2</b>. Control path: Dashboard → Node-RED → FX5U → output device.` },

  // ───────────── W16 · Protocols & Modbus ─────────────
  { id: "b1", topic: "modbus", ref: "industrial-protocol", concept: "Definition of industrial protocol",
    q: m`What is an <b>industrial protocol</b>?`,
    opts: ["A set of rules and conventions defining how devices format, transmit and interpret data",
           "The physical cable and connector between two devices",
           "A flow-based programming tool for dashboards",
           "The pyramid level where ERP systems run"],
    ex: m`"An industrial protocol is a <b>set of rules and conventions</b> that define how devices <b>format, transmit and interpret</b> data." It connects devices at every level of the automation pyramid.` },

  { id: "b2", topic: "modbus", ref: "industrial-protocol", concept: "Automation pyramid levels",
    q: m`In the automation pyramid, at which level do <b>MES / production management</b> systems sit?`,
    img: "img/w16-p05.jpg",
    opts: ["Level 4 — Operations Management", "Level 3 — Supervisory Control", "Level 5 — Enterprise", "Level 2 — Control"],
    ex: m`1 Field (sensors, actuators, I/O) → 2 Control (PLC, DCS) → 3 Supervisory (SCADA, HMI) → <b>4 Operations Management (MES)</b> → 5 Enterprise (ERP).` },

  { id: "b3", topic: "modbus", ref: "industrial-protocol", concept: "Benefit: interoperability",
    q: m`Which benefit of industrial protocols means <b>devices from different vendors can communicate</b>?`,
    opts: ["Interoperability", "Scalability", "Efficiency", "Reliability and security"],
    ex: m`<b>Interoperability</b> — different vendors communicate. Reliability & security — stable, data integrity. Efficiency — less engineering/maintenance cost. Scalability — easy expansion to IT/cloud.` },

  { id: "b4", topic: "modbus", ref: "interface-vs-protocol", concept: "Interface vs protocol",
    q: m`Modbus TCP runs over Ethernet, and Modbus RTU runs over RS-485. What does this example show?`,
    img: "img/w16-p07.jpg",
    opts: ["Different interfaces can use the same protocol",
           "Different protocols can only use their own interface",
           "An interface and a protocol are the same thing",
           "RS-485 is a protocol and Modbus is an interface"],
    ex: m`<b>Interface</b> = how devices are connected (cables, connectors, signals). <b>Protocol</b> = how data is communicated (the "language"). Different interfaces can use the same protocol, and different protocols (Modbus TCP, PROFINET, EtherNet/IP, OPC UA, MQTT) can run over the same Ethernet interface.` },

  { id: "b5", topic: "modbus", ref: "modbus", concept: "Client-server: only client initiates",
    q: m`In Modbus communication, who can <b>start</b> a communication?`,
    img: "img/w16-p10.jpg",
    opts: ["Only the client (e.g. HMI, SCADA, PC, Node-RED)", "Only the server (e.g. PLC)", "Either side at any time", "Whichever device has the lower IP address"],
    ex: m`Modbus is <b>client-server, request-response</b>. The client sends a request (e.g. "read holding register, address 0, quantity 1"). The server (PLC) processes it and returns a response (e.g. data 1500). <b>Only the client can start communication.</b>` },

  { id: "b6", topic: "modbus", ref: "modbus-fc", concept: "FC03 read holding registers",
    q: m`Node-RED must read the production counter stored in a 16-bit read/write register. Which function code?`,
    img: "img/w16-p09.jpg",
    opts: ["FC03 — Read holding registers", "FC01 — Read coils", "FC02 — Read discrete inputs", "FC06 — Write single register"],
    ex: m`16-bit <b>read/write</b> registers = holding registers → <b>FC03</b> (1–125 points per message). FC04 reads 16-bit read-only input registers. FC01/02 read bits.` },

  { id: "b7", topic: "modbus", ref: "modbus-fc", concept: "FC05 write single coil",
    q: m`A dashboard START button must set <b>one bit</b> in the PLC. Which Modbus function code is used?`,
    opts: ["FC05 — Write single coil", "FC06 — Write single register", "FC15 (0FH) — Write multiple registers", "FC02 — Read inputs"],
    ex: m`Single binary device → <b>FC05 Write single coil</b>. FC06 writes one 16-bit register. 0FH (15) writes multiple coils; 10H (16) writes multiple registers.` },

  { id: "b8", topic: "modbus", ref: "modbus-fc", concept: "Coil vs discrete input vs input/holding register",
    q: m`Which Modbus data type is a <b>1-bit, read-only</b> value?`,
    opts: ["Discrete input (FC02)", "Coil (FC01)", "Holding register (FC03)", "Input register (FC04)"],
    ex: m`<b>Coil</b> = 1-bit R/W (FC01 read, FC05/0F write). <b>Discrete input</b> = 1-bit RO (FC02). <b>Input register</b> = 16-bit RO (FC04). <b>Holding register</b> = 16-bit R/W (FC03 read, FC06/10H write).` },

  { id: "b9", topic: "modbus", ref: "modbus-fc", concept: "FC hex codes 0FH & 10H",
    q: m`On the FX5U function-code table, what are <b>0FH</b> and <b>10H</b>?`,
    opts: ["0FH = Write multiple coils, 10H = Write multiple registers",
           "0FH = Read input registers, 10H = Mask write register",
           "0FH = Write single coil, 10H = Write single register",
           "0FH = Read/write multiple registers, 10H = Read coils"],
    ex: m`0FH (=15) <b>Write multiple coils</b> (1–1968 points). 10H (=16) <b>Write multiple registers</b> (1–123 points). 16H (=22) Mask write register; 17H (=23) Read/write multiple registers.` },

  { id: "b10", topic: "modbus", ref: "modbus-fx5u", concept: "Modbus TCP default port 502",
    q: m`What is the default port number for the FX5U <b>MODBUS/TCP Connection Module</b>?`,
    img: "img/w16-p14.jpg",
    opts: ["502", "9000", "1880", "5548"],
    ex: m`Default <b>502</b>. Allowed range: 1–5548 and 5570–65534. 9000 was the SLMP port in W15; 1880 is the Node-RED editor.` },

  { id: "b11", topic: "modbus", ref: "modbus-fx5u", concept: "Enable MODBUS/TCP & Device Assignment",
    q: m`Besides adding the MODBUS/TCP connection module, what must you set in the FX5U Ethernet Port parameters?`,
    img: "img/w16-p15.jpg",
    opts: ["MODBUS/TCP Settings → \"To Use or Not to Use\" = Used, and check the Device Assignment",
           "CC-Link IEF Basic Settings → Use",
           "Communication Data Code → ASCII",
           "Transmission Port Settings → Not Used"],
    ex: m`Set <b>To Use or Not to Use MODBUS/TCP Setting = Used</b>. <b>Device Assignment</b> maps Modbus addresses to PLC memory (e.g. coil 0 → Y0, coil 8192 → M0, input 0 → X0, holding register 0 → D0).` },

  { id: "b12", topic: "modbus", ref: "modbus-fx5u", concept: "Default device map (coil 8192 = M0)",
    q: m`A Node-RED <b>Modbus-Write</b> node uses <b>FC 5</b> with <b>address 8192</b>. With the default FX5U device assignment, which PLC device is written?`,
    img: "img/w16-p16.jpg",
    opts: ["M0", "Y0", "D8192", "X0"],
    ex: m`Default coil allocation: Y0 starts at 0 (1024 pts), <b>M0 starts at 8192</b> (7680 pts), SM0 at 20480, L0 at 22528, B0 at 30720. So coil 8192 → M0 (and M20 → 8212). Holding registers: D0 starts at 0.` },

  { id: "b13", topic: "modbus", ref: "modbus-nodered", concept: "node-red-contrib-modbus client settings",
    q: m`In the W16 Node-RED setup, which settings does the <b>modbus-client</b> config node use?`,
    opts: ["Type TCP, Host 192.168.3.30, Port 502, Unit-Id 1", "Type Serial, COM3, 9600 baud", "Type TCP, Host 192.168.3.36, Port 9000, frame 3E", "Type UDP, Host localhost, Port 1880"],
    ex: m`Package <b>node-red-contrib-modbus</b> (Modbus-Read, Getter, Flex-Getter, Write, Flex-Write, Server…). Client: name FX5U_MODBUS, <b>TCP</b>, host <b>192.168.3.30</b>, port <b>502</b>, Unit-Id <b>1</b>, timeout 1000 ms, reconnect on timeout.` },
];
